//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Estudiantes.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EstudiantessEntities : DbContext
    {
        public EstudiantessEntities()
            : base("name=EstudiantessEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<materia> materias { get; set; }
        public virtual DbSet<nota> notas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
